name: Build Packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  windows-installer:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable-x86_64-pc-windows-msvc

      - name: Install Dependencies
        run: |
          choco install cmake ninja pkgconfiglite innosetup -y
          
      - name: Build
        run: |
          cmake -G "Ninja" -B build -DBUILD_INSTALLER=ON
          cmake --build build

      - name: Find Installer
        id: find_installer
        run: |
          $installerPath = Get-ChildItem -Path build\bin -Recurse -Name '*installer.exe' | Select-Object -First 1
          echo "installer_path=build\bin\$installerPath" >> $env:GITHUB_ENV
        
      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: ${{ env.installer_path }}
          
  flatpak-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Pkg Config Path
        run: export PKG_CONFIG_PATH="/usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH"

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake\
            ninja-build
        
      - name: Generate Flatpak Manifest
        run: |
          cmake -G "Ninja" -B flatpak-build -DBUILD_FLATPAK=ON
          cmake --build flatpak-build
          
      - name: Find Manifest
        id: find_manifest
        run: |
          manifest_path=$(find flatpak-build -name '*.yml' -print -quit)
          echo "Manifest found: $manifest_path"
          echo "manifest_path=$manifest_path" >> $GITHUB_ENV
        
      - name: Upload Manifest
        uses: actions/upload-artifact@v4
        with:
          name: flatpak-manifest
          path: ${{ env.manifest_path }}
          
  create-release:
    needs: [windows-installer, flatpak-manifest]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Download Windows Installer
        uses: actions/download-artifact@v4
        with:
          name: windows-installer

      - name: Download Flatpak Manifest
        uses: actions/download-artifact@v4
        with:
          name: flatpak-manifest

      - name: Find Downloaded Files
        id: find_files
        run: |
          installer_path=$(find . -name '*installer.exe' -print -quit)
          manifest_path=$(find . -name '*.yml' -print -quit)
          echo "installer_path=$installer_path" >> $GITHUB_ENV
          echo "manifest_path=$manifest_path" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.sha }}
          files: |
            ${{ env.installer_path }}
            ${{ env.manifest_path }}